
OK = 'ok'
ERROR_EXECUTE = 'Error writing to database'
ERROR_NOT_CONNECTED = 'Error not connected to database'
ERROR_NAME_ALREADY_EXIST = 'Error name already exist in table'
ERROR_NOT_EXIST = 'Error Element you like to acces does not exist'
ERROR_HOME_NOT_EXIST = 'Error the home does not exist'
ERROR_NO_PERMISSION = 'Error you do not have the permission'
ERROR_FRIEND_NOT_EXIST = 'Error the friend does not exist'
ERROR_FRIEND_ALREADY_ADDED = 'Error the friend has already your permission'
ERROR_FRIEND_NOT_ADDED = 'Error the friend is not on your list'
ERROR_PARAMETER_NOT_VALID = 'Error parameter are not valid'
ERROR_CHAT_ID_EXIST = 'Error chat_id already exist'
